#!/bin/bash

# This script prepares, on the host, what every node of the CCS environment shares:
#
#   ca/root-ca.pem, ca/root-ca.key  The root CA every node issues its own certificates from. The
#                                   clusters must share it to trust each other's transport layer.
#   credentials.env                 Passwords handed to the packages instead of generating them.
#                                   Only WAZUH_MANAGER_WUI_PASSWORD is required: the dashboard on
#                                   the CCS node must know it for both remote Wazuh servers.
#
# Anything already in place is kept, so you can provide your own CA or credentials beforehand.
# Usage: ./pre-start.sh

set -euo pipefail

cd "$(dirname "$0")"

CA_DIR="ca"
CREDENTIALS="credentials.env"

# 32 characters satisfying the password policy of the packages: 12 to 64 characters from
# A-Z a-z 0-9 . , _ + : @ % ^ = ~ - with at least one of each class.
generate_password() {
    local password
    while :; do
        password=$(LC_ALL=C tr -dc 'A-Za-z0-9._+:@%^=~-' < /dev/urandom | head -c 32 || true)
        if [[ ${password} =~ [[:upper:]] && ${password} =~ [[:lower:]] && ${password} =~ [[:digit:]] && ${password} =~ [^[:alnum:]] ]]; then
            printf '%s' "${password}"
            return
        fi
    done
}

if [ -f "${CA_DIR}/root-ca.pem" ] && [ -f "${CA_DIR}/root-ca.key" ]; then
    echo "Using the root CA in ${CA_DIR}/"
elif [ -f "${CA_DIR}/root-ca.pem" ] || [ -f "${CA_DIR}/root-ca.key" ]; then
    echo "${CA_DIR}/ must hold both root-ca.pem and root-ca.key, or neither" >&2
    exit 1
else
    echo "Creating the root CA in ${CA_DIR}/"
    mkdir -p "${CA_DIR}"
    # The same subject and extensions as the CA the packages mint for themselves.
    (
        umask 077
        openssl req -x509 -new -nodes -newkey rsa:2048 -sha256 -days 3650 -batch \
            -keyout "${CA_DIR}/root-ca.key" -out "${CA_DIR}/root-ca.pem" -config <(printf '%s\n' \
                '[req]' \
                'distinguished_name = dn' \
                'x509_extensions = v3_ca' \
                'prompt = no' \
                '[dn]' \
                'OU = Wazuh' \
                'O = Wazuh' \
                'L = California' \
                '[v3_ca]' \
                'basicConstraints = critical, CA:TRUE' \
                'keyUsage = critical, keyCertSign, cRLSign' \
                'subjectKeyIdentifier = hash' \
                'authorityKeyIdentifier = keyid:always') 2> /dev/null
    )
    chmod 644 "${CA_DIR}/root-ca.pem"
fi

if [ ! -f "${CREDENTIALS}" ]; then
    echo "Creating ${CREDENTIALS}"
    (
        umask 077
        cat > "${CREDENTIALS}" << EOF
# Passwords for the Wazuh packages of the CCS environment, copied to /etc/wazuh/credentials.env on
# every node. Any password not set here is generated by the packages on each node.
WAZUH_MANAGER_WUI_PASSWORD=$(generate_password)
EOF
    )
elif ! grep -q '^WAZUH_MANAGER_WUI_PASSWORD=' "${CREDENTIALS}"; then
    echo "Adding WAZUH_MANAGER_WUI_PASSWORD to ${CREDENTIALS}"
    # Keep the file newline-terminated: the packages refuse to write to one that is not.
    [ -z "$(tail -c 1 "${CREDENTIALS}")" ] || echo >> "${CREDENTIALS}"
    echo "WAZUH_MANAGER_WUI_PASSWORD=$(generate_password)" >> "${CREDENTIALS}"
else
    echo "Using ${CREDENTIALS}"
fi
