name: "Branch Resolver"
description: "Determine correct branches for dependent repos"
inputs:
  branch:
    description: "Branch to check"
    required: true
outputs:
  wazuh_indexer_plugins_branch:
    description: "Branch for wazuh-indexer-plugins"
    value: ${{ steps.resolve.outputs.wazuh_indexer_plugins_branch }}
  wazuh_indexer_reporting_branch:
    description: "Branch for wazuh-indexer-reporting"
    value: ${{ steps.resolve.outputs.wazuh_indexer_reporting_branch }}
runs:
  using: "composite"
  steps:
    - id: resolve
      run: |
        eval $(${{ github.action_path }}/resolve-branches.sh "${{ inputs.branch }}" | awk -F= '{gsub("-", "_", $1); print toupper($1)"_BRANCH="$2}')
        echo "wazuh_indexer_plugins_branch=$WAZUH_INDEXER_PLUGINS_BRANCH" >> $GITHUB_OUTPUT
        echo "wazuh_indexer_reporting_branch=$WAZUH_INDEXER_REPORTING_BRANCH" >> $GITHUB_OUTPUT
      shell: bash
