services:

  wazuh-indexer-builder:
    image: wazuh-indexer-builder:${VERSION}
    container_name: wazuh-indexer-builder_${VERSION}
    build:
      context: ./../..
      dockerfile: ${REPO_PATH}/docker/builder/Dockerfile
    volumes:
     - ${REPO_PATH}:/home/wazuh-indexer
     - wazuh-indexer-plugins:/home/wazuh-indexer/wazuh-indexer-plugins
     - wazuh-indexer-reporting:/home/wazuh-indexer/wazuh-indexer-reporting
    entrypoint: ["/bin/bash", "/entrypoint.sh"]
    user: "1000:1000"
    working_dir: /home/wazuh-indexer
volumes:
  wazuh-indexer-plugins:
  wazuh-indexer-reporting:
