Vagrant.configure("2") do |config|
    config.vm.define "indexer_1" do |indexer_1|
        indexer_1.vm.box = "generic/rhel9"
        indexer_1.vm.synced_folder ".", "/vagrant"
        indexer_1.vm.network "private_network", ip: "192.168.56.10"
        indexer_1.vm.hostname = "node-1"
        indexer_1.vm.provider "libvirt" do |vb|
            vb.memory = "6144"
            vb.cpus = "4"
        end
        indexer_1.vm.provision "shell", inline: <<-SHELL
            sudo systemctl stop firewalld
            sudo systemctl disable firewalld
            sudo yum clean all
            # Add node-2 to /etc/hosts
            echo "192.168.56.11 node-2" >> /etc/hosts
            # Generate certificates
            cp /vagrant/config.yml config.yml
            curl -sO https://packages.wazuh.com/4.9/wazuh-certs-tool.sh
            bash ./wazuh-certs-tool.sh -A
            # Compress and share certificates
            tar -cvf ./wazuh-certificates.tar -C ./wazuh-certificates/ .
            rm -rf ./wazuh-certificates *.yml *.log *.sh
            cp wazuh-certificates.tar /vagrant/wazuh-certificates.tar
        SHELL
    end
    config.vm.define "indexer_2" do |indexer_2|
        indexer_2.vm.box = "generic/ubuntu2204"
        indexer_2.vm.synced_folder ".", "/vagrant"
        indexer_2.vm.network "private_network", ip: "192.168.56.11"
        indexer_2.vm.hostname = "node-2"
        indexer_2.vm.provider "libvirt" do |vb|
            vb.memory = "6144"
            vb.cpus = "4"
        end
        indexer_2.vm.provision "shell", inline: <<-SHELL
            sudo systemctl stop ufw
            sudo systemctl disable ufw
            # Add node-1 to /etc/hosts
            echo "192.168.56.10 node-1" >> /etc/hosts
            # Copy generated certificates
            cp /vagrant/wazuh-certificates.tar wazuh-certificates.tar
        SHELL
    end
end
