version: "3.9"

services:

  wazuh-indexer:
    image: wazuh-indexer-dev:${VERSION}
    container_name: wazuh-indexer-dev-${VERSION}
    build:
      context: ./..
      dockerfile: ${REPO_PATH}/docker/images/wi-dev.Dockerfile
    ports:
      # OpenSearch REST API
      - 9200:9200
      # Cross-cluster search
      # - 9250:9250
      # Node communication and transport
      # - 9300:9300
      # Performance Analyzer
      # - 9600:9600
    expose:
      - 9200
    volumes:
      - ${REPO_PATH}:/home/wazuh-indexer/app
    entrypoint: ['tail', '-f', '/dev/null']
    user: "1000:1000"
    working_dir: /home/wazuh-indexer/app
