
# ---------------------------------------------------------------------#
# Wazuh Indexer Default Users
# ---------------------------------------------------------------------#

wazuh-manager:
  hash: "${WAZUH_INDEXER_MANAGER_PASSWORD}"
  reserved: true
  backend_roles: []
  description: "Wazuh Manager user with write-only access to stateless (events) indexes, read/write/delete access to stateful (states) indexes, and read access to consumers, threat intelligence content, and active-responses indexes."
