wazuhserver:
  # The hash is the hash of the password "wazuhserver"
  hash: "$2b$12$F2AcDHixU0NJelALgC4LU.7Ac5OsxgXPh5kALHiuBu2ftstDBHoQ."
  reserved: false
  backend_roles:
    - "server-stateful-read-write"
    - "server-stateless-write-only"
  description: "Server user with read/write access to stateful and write-only access to stateless indexes"
wazuhdashboard:
  # The hash is the hash of the password "wazuhdashboard"
  hash: "$2b$12$HYNejpgq0WUQ3a4hFvbGOOtvgE0H/pH7OqMhlHHRM0Ziu4V3EF/8y"
  reserved: false
  backend_roles:
    - "dashboard-stateful-read-only"
    - "dashboard-stateless-read-only"
    - "dashboard-stateless-read-write"
    - "dashboard-stateless-management"
  description: "Dashboard user with read access to stateful and stateless indexes, and write access to stateless management indexes"
