
# ---------------------------------------------------------------------#
# Wazuh Indexer Default Roles
# ---------------------------------------------------------------------#

# Read access to Wazuh indexes for the internal user of Wazuh Dashboard.
dashboard_server:
  reserved: true
  hidden: false
  cluster_permissions:
    - "cluster:admin/opensearch/notifications/configs/get"
  index_permissions:
    - index_patterns:
      - "wazuh-*"
      allowed_actions:
      - "read"
  tenant_permissions: []
  static: false

# Allows users to read Wazuh settings.
wazuh_settings_read:
  reserved: true
  hidden: false
  cluster_permissions: []
  index_permissions:
    - index_patterns:
        - ".wazuh-settings"
      allowed_actions:
        - "read"
  tenant_permissions: []
  static: true

# Allows to write to the .wazuh-settings index (through the REST API).
wazuh_settings_write:
  reserved: true
  hidden: false
  cluster_permissions:
    - "plugin:wazuh/settings"
  index_permissions: []
  tenant_permissions: []
  static: true

# Allows users to read Wazuh consumers status.
wazuh_consumers_read:
  reserved: true
  hidden: false
  cluster_permissions: []
  index_permissions:
    - index_patterns:
        - ".wazuh-cti-consumers"
      allowed_actions:
        - "read"
  tenant_permissions: []
  static: true

# Allows users to read Wazuh threat intelligence content.
wazuh_threatintel_read:
  reserved: true
  hidden: false
  cluster_permissions: []
  index_permissions:
    - index_patterns:
        - "wazuh-threatintel-*"
      allowed_actions:
        - "read"
  tenant_permissions: []
  static: true

# Allows users to read from data streams with the prefix "wazuh-events-".
wazuh_events_read:
  reserved: true
  hidden: false
  cluster_permissions: []
  index_permissions:
    - index_patterns:
        - "wazuh-events-*"
      allowed_actions:
        - "read"
  tenant_permissions: []
  static: true

# Allows users to write to data streams with the prefix "wazuh-events-".
wazuh_events_write:
  reserved: true
  hidden: false
  cluster_permissions: []
  index_permissions:
    - index_patterns:
        - "wazuh-events-*"
      allowed_actions:
        - "index"
  tenant_permissions: []
  static: true

# Allows users to read from regular indexes with the prefix "wazuh-states-".
wazuh_states_read:
  reserved: true
  hidden: false
  cluster_permissions: []
  index_permissions:
    - index_patterns:
        - "wazuh-states-*"
      allowed_actions:
        - "read"
  tenant_permissions: []
  static: true

# Allows users to write to regular indexes with the prefix "wazuh-states-".
wazuh_states_write:
  reserved: true
  hidden: false
  cluster_permissions: []
  index_permissions:
    - index_patterns:
        - "wazuh-states-*"
      allowed_actions:
        - "index"
        - "delete"
  tenant_permissions: []
  static: true

# Allows users to read data streams with the prefix "wazuh-metrics-".
wazuh_metrics_read:
  reserved: true
  hidden: false
  cluster_permissions: []
  index_permissions:
    - index_patterns:
        - "wazuh-metrics-*"
      allowed_actions:
        - "read"
  tenant_permissions: []
  static: true

# Allows users to write to data streams with the prefix "wazuh-metrics-".
wazuh_metrics_write:
  reserved: true
  hidden: false
  cluster_permissions: []
  index_permissions:
    - index_patterns:
        - "wazuh-metrics-*"
      allowed_actions:
        - "index"
  tenant_permissions: []
  static: true

# Allows users to read from data streams with the prefix "wazuh-active-responses-".
wazuh_active_responses_read:
  reserved: true
  hidden: false
  cluster_permissions: []
  index_permissions:
    - index_patterns:
        - "wazuh-active-responses-*"
      allowed_actions:
        - "read"
  tenant_permissions: []
  static: true

# Allows users to view the subscription details.
wazuh_cm_subscription_read:
  reserved: true
  hidden: false
  cluster_permissions:
    - "plugin:content_manager/subscription_get"
  index_permissions: []
  tenant_permissions: []
  static: true

# Allows users to update and delete subscriptions.
wazuh_cm_subscription_write:
  reserved: true
  hidden: false
  cluster_permissions:
    - "plugin:content_manager/subscription_post"
    - "plugin:content_manager/subscription_delete"
  index_permissions: []
  tenant_permissions: []
  static: true

# Allows users to trigger on-demand content updates.
wazuh_cm_update:
  reserved: true
  hidden: false
  cluster_permissions:
    - "plugin:content_manager/update"
  index_permissions: []
  tenant_permissions: []
  static: true

# Allows users to manage key-value databases (kvdbs) in the Content Manager plugin.
wazuh_cm_kvdbs_write:
  reserved: true
  hidden: false
  cluster_permissions:
    - "plugin:content_manager/kvdb_create"
    - "plugin:content_manager/kvdb_update"
    - "plugin:content_manager/kvdb_delete"
  index_permissions: []
  tenant_permissions: []
  static: true

# Allows users to manage decoders in the Content Manager plugin.
wazuh_cm_decoders_write:
  reserved: true
  hidden: false
  cluster_permissions:
    - "plugin:content_manager/decoder_create"
    - "plugin:content_manager/decoder_update"
    - "plugin:content_manager/decoder_delete"
  index_permissions: []
  tenant_permissions: []
  static: true

# Allows users to manage filters in the Content Manager plugin.
wazuh_cm_filters_write:
  reserved: true
  hidden: false
  cluster_permissions:
    - "plugin:content_manager/filter_create"
    - "plugin:content_manager/filter_update"
    - "plugin:content_manager/filter_delete"
  index_permissions: []
  tenant_permissions: []
  static: true

# Allows users to manage rules in the Content Manager plugin.
wazuh_cm_rules_write:
  reserved: true
  hidden: false
  cluster_permissions:
    - "plugin:content_manager/rule_create"
    - "plugin:content_manager/rule_update"
    - "plugin:content_manager/rule_delete"
  index_permissions: []
  tenant_permissions: []
  static: true

# Allows users to manage integrations in the Content Manager plugin.
wazuh_cm_integrations_write:
  reserved: true
  hidden: false
  cluster_permissions:
    - "plugin:content_manager/integration_create"
    - "plugin:content_manager/integration_update"
    - "plugin:content_manager/integration_delete"
  index_permissions: []
  tenant_permissions: []
  static: true

# Allows users to execute logtests in the Content Manager plugin.
wazuh_cm_logtest:
  reserved: true
  hidden: false
  cluster_permissions:
    - "plugin:content_manager/engine_logtest"
    - "plugin:content_manager/engine_logtest_normalization"
    - "plugin:content_manager/engine_logtest_detection"
  index_permissions: []
  tenant_permissions: []
  static: true

# Allows users to preview and execute content promotions in the Content Manager plugin.
wazuh_cm_space_promote:
  reserved: true
  hidden: false
  cluster_permissions:
    - "plugin:content_manager/promote_preview"
    - "plugin:content_manager/promote"
  index_permissions: []
  tenant_permissions: []
  static: true

# Allows users to manage policies in the Content Manager plugin.
wazuh_cm_policy_write:
  reserved: true
  hidden: false
  cluster_permissions:
    - "plugin:content_manager/policy_update"
  index_permissions: []
  tenant_permissions: []
  static: true

# Allows users to delete content from spaces in the Content Manager plugin.
wazuh_cm_space_reset:
  reserved: true
  hidden: false
  cluster_permissions:
    - "plugin:content_manager/space_delete"
  index_permissions: []
  tenant_permissions: []
  static: true
