# Wazuh monitoring and statistics index permissions
manage_wazuh_index:
  reserved: true
  hidden: false
  cluster_permissions:
    - "cluster:admin/opensearch/notifications/configs/get"
  index_permissions:
  - index_patterns:
    - "wazuh-*"
    allowed_actions:
    - "read"
  tenant_permissions: []
  static: false

# Wazuh index roles
settings:
  reserved: true
  hidden: false
  cluster_permissions:
    - "cluster:monitor/health"
  index_permissions:
    - index_patterns:
        - ".wazuh-settings"
      allowed_actions:
        - "read"
  tenant_permissions: []
  static: true

consumers:
  reserved: true
  hidden: false
  cluster_permissions:
    - "cluster:monitor/health"
  index_permissions:
    - index_patterns:
        - ".wazuh-cti-consumers"
      allowed_actions:
        - "read"
  tenant_permissions: []
  static: true

content:
  reserved: true
  hidden: false
  cluster_permissions:
    - "cluster:monitor/health"
  index_permissions:
    - index_patterns:
        - "wazuh-threatintel-*"
      allowed_actions:
        - "read"
  tenant_permissions: []
  static: true

stateless:
  reserved: true
  hidden: false
  cluster_permissions: []
  index_permissions:
    - index_patterns:
        - "wazuh-events-*"
      allowed_actions:
        - "index"
  tenant_permissions: []
  static: true

stateful:
  reserved: true
  hidden: false
  cluster_permissions: []
  index_permissions:
    - index_patterns:
        - "wazuh-states-*"
      allowed_actions:
        - "read"
        - "index"
        - "delete"
  tenant_permissions: []
  static: true

metrics:
  reserved: true
  hidden: false
  cluster_permissions:
    - "cluster:monitor/health"
  index_permissions:
    - index_patterns:
        - "wazuh-metrics-*"
      allowed_actions:
        - "index"
  tenant_permissions: []
  static: true

active-responses:
  reserved: true
  hidden: false
  cluster_permissions: []
  index_permissions:
    - index_patterns:
        - "wazuh-active-responses-*"
      allowed_actions:
        - "read"
  tenant_permissions: []
  static: true

# Plugin Setup
setup_settings_management:
  reserved: true
  hidden: false
  cluster_permissions:
    - "plugin:wazuh/settings"
  index_permissions:
    - index_patterns:
        - ".wazuh-settings"
      allowed_actions:
        - "read"
  tenant_permissions: []
  static: true

# Plugin Content Manager
cm_subscription_read:
  reserved: true
  hidden: false
  cluster_permissions:
    - "plugin:content_manager/subscription_get"
  index_permissions: []
  tenant_permissions: []
  static: true

cm_subscription_write:
  reserved: true
  hidden: false
  cluster_permissions:
    - "plugin:content_manager/subscription_post"
    - "plugin:content_manager/subscription_delete"
  index_permissions: []
  tenant_permissions: []
  static: true

cm_update_management:
  reserved: true
  hidden: false
  cluster_permissions:
    - "plugin:content_manager/update"
  index_permissions:
    - index_patterns:
        - "wazuh-threatintel-*"
      allowed_actions:
        - "read"
  tenant_permissions: []
  static: true

cm_kvdb_management:
  reserved: true
  hidden: false
  cluster_permissions:
    - "plugin:content_manager/kvdb_create"
    - "plugin:content_manager/kvdb_update"
    - "plugin:content_manager/kvdb_delete"
  index_permissions:
    - index_patterns:
        - "wazuh-threatintel-kvdbs-*"
      allowed_actions:
        - "read"
  tenant_permissions: []
  static: true

cm_decoder_management:
  reserved: true
  hidden: false
  cluster_permissions:
    - "plugin:content_manager/decoder_create"
    - "plugin:content_manager/decoder_update"
    - "plugin:content_manager/decoder_delete"
  index_permissions:
    - index_patterns:
        - "wazuh-threatintel-decoders-*"
      allowed_actions:
        - "read"
  tenant_permissions: []
  static: true

cm_filter_management:
  reserved: true
  hidden: false
  cluster_permissions:
    - "plugin:content_manager/filter_create"
    - "plugin:content_manager/filter_update"
    - "plugin:content_manager/filter_delete"
  index_permissions:
    - index_patterns:
        - "wazuh-threatintel-filters-*"
      allowed_actions:
        - "read"
  tenant_permissions: []
  static: true

cm_rule_management:
  reserved: true
  hidden: false
  cluster_permissions:
    - "plugin:content_manager/rule_create"
    - "plugin:content_manager/rule_update"
    - "plugin:content_manager/rule_delete"
  index_permissions:
    - index_patterns:
        - "wazuh-threatintel-*"
        - "opensearch-sap-*-*"
        - ".opensearch-sap-detectors-config"
      allowed_actions:
        - "read"
  tenant_permissions: []
  static: true

cm_integration_management:
  reserved: true
  hidden: false
  cluster_permissions:
    - "plugin:content_manager/integration_create"
    - "plugin:content_manager/integration_update"
    - "plugin:content_manager/integration_delete"
  index_permissions:
    - index_patterns:
        - "wazuh-threatintel-integrations-*"
        - "opensearch-sap-*-*"
        - ".opensearch-sap-detectors-config"
      allowed_actions:
        - "read"
  tenant_permissions: []
  static: true

cm_logtest:
  reserved: true
  hidden: false
  cluster_permissions:
    - "plugin:content_manager/engine_logtest"
    - "plugin:content_manager/engine_logtest_normalization"
    - "plugin:content_manager/engine_logtest_detection"
  index_permissions: []
  tenant_permissions: []
  static: true

cm_promote_management:
  reserved: true
  hidden: false
  cluster_permissions:
    - "plugin:content_manager/promote_preview"
    - "plugin:content_manager/promote"
  index_permissions:
    - index_patterns:
        - "wazuh-threatintel-*"
      allowed_actions:
        - "read"
  tenant_permissions: []
  static: true

cm_policy_management:
  reserved: true
  hidden: false
  cluster_permissions:
    - "plugin:content_manager/policy_update"
  index_permissions:
    - index_patterns:
        - "wazuh-threatintel-policies-*"
      allowed_actions:
        - "read"
  tenant_permissions: []
  static: true

cm_space_management:
  reserved: true
  hidden: false
  cluster_permissions:
    - "plugin:content_manager/space_delete"
  index_permissions:
    - index_patterns:
        - "wazuh-threatintel-*"
      allowed_actions:
        - "read"
  tenant_permissions: []
  static: true

# Plugin SAP
sap_detector_read:
  reserved: true
  hidden: false
  cluster_permissions:
    - "cluster:admin/opensearch/securityanalytics/detector/get"
    - "cluster:admin/opensearch/securityanalytics/detector/search"
  index_permissions:
    - index_patterns:
        - ".opensearch-sap-*-findings-*"
      allowed_actions:
        - "read"
  tenant_permissions: []
  static: true

sap_detector_write:
  reserved: true
  hidden: false
  cluster_permissions:
    - "cluster:admin/opensearch/securityanalytics/detector/write"
    - "cluster:admin/opensearch/securityanalytics/detector/delete"
  index_permissions:
    - index_patterns:
        - "opensearch-sap-*-*"
        - ".opensearch-sap-detectors-config"
      allowed_actions:
        - "read"
  tenant_permissions: []
  static: true
