
# ---------------------------------------------------------------------#
# Wazuh Indexer Default Roles Mappings
# ---------------------------------------------------------------------#

dashboard_server:
  reserved: true
  hidden: false
  users:
    - "kibanaserver"

wazuh_settings_read:
  reserved: true
  hidden: false
  users:
    - "wazuh-admin"
    - "wazuh-readonly"

wazuh_settings_write:
  reserved: true
  hidden: false
  users:
    - "wazuh-admin"

wazuh_consumers_read:
  reserved: true
  hidden: false
  users:
    - "wazuh-server"
    - "wazuh-admin"
    - "wazuh-content-manager"
    - "wazuh-readonly"

wazuh_threatintel_read:
  reserved: true
  hidden: false
  users:
    - "wazuh-server"
    - "wazuh-admin"
    - "wazuh-content-manager"
    - "wazuh-readonly"

wazuh_events_read:
  reserved: true
  hidden: false
  users:
    - "wazuh-admin"
    - "wazuh-readonly"

wazuh_events_write:
  reserved: true
  hidden: false
  users:
    - "wazuh-server"

wazuh_states_read:
  reserved: true
  hidden: false
  users:
    - "wazuh-server"
    - "wazuh-admin"
    - "wazuh-readonly"

wazuh_states_write:
  reserved: true
  hidden: false
  users:
    - "wazuh-server"

wazuh_metrics_read:
  reserved: true
  hidden: false
  users:
    - "wazuh-server"
    - "wazuh-admin"
    - "wazuh-readonly"

wazuh_metrics_write:
  reserved: true
  hidden: false
  users:
    - "wazuh-server"

wazuh_active_responses_read:
  reserved: true
  hidden: false
  users:
    - "wazuh-server"
    - "wazuh-admin"
    - "wazuh-readonly"

# Plugin Content Manager
wazuh_cm_subscription_read:
  reserved: true
  hidden: false
  users:
    - "wazuh-admin"
    - "wazuh-content-manager"
    - "wazuh-readonly"

wazuh_cm_subscription_write:
  reserved: true
  hidden: false
  users:
    - "wazuh-admin"

wazuh_cm_update:
  reserved: true
  hidden: false
  users:
    - "wazuh-admin"
    - "wazuh-content-manager"

wazuh_cm_kvdb_management:
  reserved: true
  hidden: false
  users:
    - "wazuh-content-manager"
    - "wazuh-admin"

wazuh_cm_decoder_management:
  reserved: true
  hidden: false
  users:
    - "wazuh-content-manager"
    - "wazuh-admin"

wazuh_cm_filter_management:
  reserved: true
  hidden: false
  users:
    - "wazuh-content-manager"
    - "wazuh-admin"

wazuh_cm_rule_management:
  reserved: true
  hidden: false
  users:
    - "wazuh-content-manager"
    - "wazuh-admin"

wazuh_cm_integration_management:
  reserved: true
  hidden: false
  users:
    - "wazuh-content-manager"
    - "wazuh-admin"

wazuh_cm_logtest:
  reserved: true
  hidden: false
  users:
    - "wazuh-content-manager"
    - "wazuh-admin"

wazuh_cm_promote_management:
  reserved: true
  hidden: false
  users:
    - "wazuh-content-manager"
    - "wazuh-admin"

wazuh_cm_policy_management:
  reserved: true
  hidden: false
  users:
    - "wazuh-admin"
    - "wazuh-content-manager"

wazuh_cm_space_reset:
  reserved: true
  hidden: false
  users:
    - "wazuh-admin"
    - "wazuh-content-manager"

security_analytics_read_access:
  reserved: true
  hidden: false
  users:
    - "wazuh-admin"
    - "wazuh-readonly"
    - "wazuh-content-manager"

security_analytics_full_access:
  reserved: true
  hidden: false
  users:
    - "wazuh-admin"
    - "wazuh-content-manager"
