# Wazuh monitoring and statistics index permissions
manage_wazuh_index:
  reserved: true
  hidden: false
  backend_roles: []
  hosts: []
  users:
  - "kibanaserver"
  and_backend_roles: []

# Wazuh index roles
settings:
  reserved: true
  hidden: false
  backend_roles: []
  hosts: []
  users:
    - "wazuh-dashboard"
    - "wazuh-admin"
    - "wazuh-readonly"
  and_backend_roles: []

consumers:
  reserved: true
  hidden: false
  backend_roles: []
  hosts: []
  users:
    - "wazuh-server"
    - "wazuh-dashboard"
    - "wazuh-admin"
    - "wazuh-content-manager"
    - "wazuh-readonly"
  and_backend_roles: []

content:
  reserved: true
  hidden: false
  backend_roles: []
  hosts: []
  users:
    - "wazuh-dashboard"
    - "wazuh-admin"
    - "wazuh-content-manager"
    - "wazuh-readonly"
  and_backend_roles: []

stateless-write:
  reserved: true
  hidden: false
  backend_roles: []
  hosts: []
  users:
    - "wazuh-server"
    - "wazuh-admin"
  and_backend_roles: []

stateless-read:
  reserved: true
  hidden: false
  backend_roles: []
  hosts: []
  users:
    - "wazuh-admin"
    - "wazuh-readonly"
    - "wazuh-dashboard"
  and_backend_roles: []

stateful:
  reserved: true
  hidden: false
  backend_roles: []
  hosts: []
  users:
    - "wazuh-server"
    - "wazuh-admin"
  and_backend_roles: []

stateful-read:
  reserved: true
  hidden: false
  backend_roles: []
  hosts: []
  users:
    - "wazuh-readonly"
    - "wazuh-dashboard"
  and_backend_roles: []

metrics:
  reserved: true
  hidden: false
  backend_roles: []
  hosts: []
  users:
    - "wazuh-dashboard"
    - "wazuh-admin"
  and_backend_roles: []

active-responses:
  reserved: true
  hidden: false
  backend_roles: []
  hosts: []
  users:
    - "wazuh-server"
    - "wazuh-admin"
    - "wazuh-dashboard"
  and_backend_roles: []

# Plugin Setup
setup_settings_management:
  reserved: true
  hidden: false
  backend_roles: []
  hosts: []
  users:
    - "wazuh-dashboard"
    - "wazuh-admin"
  and_backend_roles: []

# Plugin Content Manager
cm_subscription_read:
  reserved: true
  hidden: false
  backend_roles: []
  hosts: []
  users:
    - "wazuh-dashboard"
    - "wazuh-admin"
    - "wazuh-content-manager"
    - "wazuh-readonly"
  and_backend_roles: []

cm_subscription_write:
  reserved: true
  hidden: false
  backend_roles: []
  hosts: []
  users:
    - "wazuh-dashboard"
    - "wazuh-admin"
    - "wazuh-content-manager"
  and_backend_roles: []

cm_update_management:
  reserved: true
  hidden: false
  backend_roles: []
  hosts: []
  users:
    - "wazuh-dashboard"
    - "wazuh-admin"
    - "wazuh-content-manager"
  and_backend_roles: []

cm_kvdb_management:
  reserved: true
  hidden: false
  backend_roles: []
  hosts: []
  users:
    - "wazuh-dashboard"
    - "wazuh-content-manager"
    - "wazuh-admin"
  and_backend_roles: []

cm_decoder_management:
  reserved: true
  hidden: false
  backend_roles: []
  hosts: []
  users:
    - "wazuh-dashboard"
    - "wazuh-content-manager"
    - "wazuh-admin"
  and_backend_roles: []

cm_filter_management:
  reserved: true
  hidden: false
  backend_roles: []
  hosts: []
  users:
    - "wazuh-dashboard"
    - "wazuh-content-manager"
    - "wazuh-admin"
  and_backend_roles: []

cm_rule_management:
  reserved: true
  hidden: false
  backend_roles: []
  hosts: []
  users:
    - "wazuh-dashboard"
    - "wazuh-content-manager"
    - "wazuh-admin"
  and_backend_roles: []

cm_integration_management:
  reserved: true
  hidden: false
  backend_roles: []
  hosts: []
  users:
    - "wazuh-dashboard"
    - "wazuh-content-manager"
    - "wazuh-admin"
  and_backend_roles: []

cm_logtest:
  reserved: true
  hidden: false
  backend_roles: []
  hosts: []
  users:
    - "wazuh-dashboard"
    - "wazuh-content-manager"
    - "wazuh-admin"
  and_backend_roles: []

cm_promote_management:
  reserved: true
  hidden: false
  backend_roles: []
  hosts: []
  users:
    - "wazuh-dashboard"
    - "wazuh-content-manager"
    - "wazuh-admin"
  and_backend_roles: []

cm_policy_management:
  reserved: true
  hidden: false
  backend_roles: []
  hosts: []
  users:
    - "wazuh-dashboard"
    - "wazuh-admin"
    - "wazuh-content-manager"
  and_backend_roles: []

cm_space_management:
  reserved: true
  hidden: false
  backend_roles: []
  hosts: []
  users:
    - "wazuh-dashboard"
    - "wazuh-admin"
    - "wazuh-content-manager"
  and_backend_roles: []

# Plugin SAP
sap_detector_read:
  reserved: true
  hidden: false
  backend_roles: []
  hosts: []
  users:
    - "wazuh-dashboard"
    - "wazuh-admin"
    - "wazuh-readonly"
  and_backend_roles: []

sap_detector_write:
  reserved: true
  hidden: false
  backend_roles: []
  hosts: []
  users:
    - "wazuh-dashboard"
    - "wazuh-admin"
  and_backend_roles: []
