---
- name: package
  title: Package
  type: group
  group: 2
  description: >
    Package related data.
  fields:
    - name: hotfix
      type: group
      level: custom
      group: 2
      description: >
        Hotfix related data.
      fields:
        - name: name
          type: keyword
          level: custom
          description: >
            Name of the Hotfix.