
nodes:
  indexer:
    - name: wazuh.indexer
      ip: "wazuh.indexer"
  server:
    - name: wazuh.manager
      ip: "wazuh.manager"
  dashboard:
    - name: wazuh.dashboard
      ip: "wazuh.dashboard"

