
name: Build and push Docker image (on push)

# This workflow runs when any of the following occur:
# - Any change is pushed to the repo

on:
    push:


jobs:
    call-docker-workflow:
        uses: ./.github/workflows/5_builderpackage_docker.yml
        secrets: inherit