name: Run Gradle Build
on:
  schedule:
    - cron: '00 8 * * 5'
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2.9.0
    
    - name: Execute Gradle build
      run: ./gradlew build
