name: Assemble (reusable)

# This workflow runs when any of the following occur:
# - Run from another workflow
on:
  workflow_call:
    inputs:
      revision:
        description: "Revision number"
        type: string
        default: "0"
      is_release:
        description: "Uses release's nomenclature"
        type: boolean
        default: false
      distribution:
        description: One of "[ 'tar', 'rpm', 'deb', 'docker' ]"
        type: string
        required: true
      architecture:
        description: One of "[ 'x64', 'arm64' ]"
        type: string
        required: true

jobs:
  r_assemble:
    runs-on: ubuntu-latest
    # Permissions to upload the package
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Run `baptizer.sh` (min)
        run: |
          name=$(bash scripts/baptizer.sh -m \
            ${{ inputs.is_release && '-x' }} \
            -a ${{ inputs.architecture }} \
            -d ${{ inputs.distribution }}  \
            -r ${{ inputs.revision }} \
          )
          echo "$name" >> $GITHUB_OUTPUT
        id: min_package

      - name: Run `baptizer.sh`
        run: |
          name=$(bash scripts/baptizer.sh \
            ${{ inputs.is_release && '-x' }} \
            -a ${{ inputs.architecture }} \
            -d ${{ inputs.distribution }}  \
            -r ${{ inputs.revision }} \
          )
          echo "$name" >> $GITHUB_OUTPUT
        id: package

      - name: Provision
        if: ${{ inputs.distribution == 'deb' }}
        run: |
          sudo bash scripts/provision.sh

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ steps.min_package.outputs.name }}
          path: artifacts/dist

      - name: Run `assemble.sh`
          mkdir -p ./artifacts/dist
          touch ./artifacts/dist/${{ steps.package.outputs.name }}
        # run: |
        #   bash scripts/assemble.sh -a ${{ inputs.architecture }} -d ${{ inputs.distribution }} -r ${{ inputs.revision }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.package.outputs.name }}
          path: artifacts/dist/${{ steps.package.outputs.name }}
          if-no-files-found: error
