name: Assemble (reusable)

env:
  TEST: true

# This workflow runs when any of the following occur:
# - Run from another workflow
on:
  workflow_call:
    inputs:
      distribution:
        description: "One of [ 'tar', 'rpm', 'deb' ]"
        default: "rpm"
        required: true
        type: string
      architecture:
        description: "One of [ 'x64', 'arm64' ]"
        default: "x64"
        required: true
        type: string
      min:
        description: "The name of the package to download."
        required: true
        type: string

jobs:
  r_assemble:
    runs-on: ubuntu-latest
    # Permissions to upload the package
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.min }}
          path: artifacts/dist

      - name: Provision
        if: ${{ inputs.distribution == 'deb' }}
        run: |
          sudo bash scripts/provision.sh

      - name: Run `assemble.sh`
        run: |
          bash scripts/assemble.sh -v ${{ vars.OPENSEARCH_VERSION }} -p linux -a ${{ inputs.architecture }} -d ${{ inputs.distribution }}

      # The package's name is stored in artifacts/artifact_name.txt.
      - name: Set package name
        id: get_name
        run: |
          echo "name=$(cat artifacts/artifact_name.txt)" >> $GITHUB_OUTPUT

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.get_name.outputs.name }}
          path: artifacts/dist/${{ steps.get_name.outputs.name }}
          if-no-files-found: error
