name: Assemble (reusable)

# This workflow runs when any of the following occur:
# - Run from another workflow
on:
  workflow_call:
    inputs:
      distribution:
        description: 'One of [ "tar", "rpm", "deb" ]'
        default: "rpm"
        required: false
        type: string
      architecture:
        description: 'One of [ "x64", "arm64" ]'
        default: "x64"
        required: false
        type: string
      name:
        required: true
        type: string

jobs:
  r_assemble:
    # runs-on: ${{ inputs.architecture }}
    runs-on: ubuntu-latest
    # Permissions to upload the package
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Test
        run: |
          echo "${{ inputs.distribution }}_${{ inputs.architecture }}"
          echo ${{ inputs.name }}

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.name }}
          path: artifacts/dist/${{ inputs.name }}

      # - name: Run `assemble.sh`
      #   run: |
      #     bash scripts/assemble.sh -v ${{ vars.OPENSEARCH_VERSION }} -p linux -a ${{ inputs.architecture }} -d ${{ inputs.distribution }}

      # - name: Upload artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      # name: ${{ steps.get_name.outputs.name }}
      # path: ${{ inputs.architecture }}/${{ inputs.distribution }}
      #     if-no-files-found: error
