name: Build minimal packages (reusable)

# This workflow runs when any of the following occur:
# - Run from another workflow
on:
  workflow_call:
    inputs:
      revision:
        description: "Revision number"
        type: string
        default: "0"
      is_release:
        description: "Uses release's nomenclature"
        type: boolean
        default: false
      distribution:
        description: One of "[ 'tar', 'rpm', 'deb', 'docker' ]"
        type: string
        required: true
      architecture:
        description: One of "[ 'x64', 'arm64' ]"
        type: string
        required: true

jobs:
  r_build_min:
    runs-on: ubuntu-latest
    # Permissions to upload the package
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Run `baptizer.sh`
        run: |
          name=$(bash scripts/baptizer.sh -m \
            ${{ inputs.is_release && '-x' }} \
            -a ${{ inputs.architecture }} \
            -d ${{ inputs.distribution }}  \
            -r ${{ inputs.revision }} \
          )
          echo "$name" >> $GITHUB_OUTPUT
        id: package

      - name: Run `build.sh`
        run: |
          mkdir -p ./artifacts/dist
          touch ./artifacts/dist/${{ steps.package.outputs.name }}
        # run: |
        #   bash scripts/build.sh -a ${{ inputs.architecture }} -d ${{ inputs.distribution }} -r ${{ inputs.revision }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.package.outputs.name }}
          path: artifacts/dist/${{ steps.package.outputs.name }}
          if-no-files-found: error
